{% set name = "xtensor-fftw" %}
{% set version = "0.2.6" %}
{% set sha256 = "82d7492db4ae5593c2e419ddf1ece660ee315b269bc9e90176812e21d47bae3b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xtensor-stack/xtensor-fftw/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake >=3.1.3
    - {{ compiler('cxx') }}
  host:
    - xtensor >=0.20.9,<0.22
    - fftw >=3.0
  run:
    - xtensor >=0.20.9,<0.22
    - fftw >=3.0

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-fftw  # [unix]
    - test -f ${PREFIX}/include/xtensor-fftw/xtensor-fftw_config.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-fftw/xtensor-fftwConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-fftw/xtensor-fftwConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtensor-fftw\xtensor-fftw_config.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-fftwConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-fftwConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/xtensor-stack/xtensor-fftw
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'FFTW bindings for xtensor'
  description: |
    xtensor-fftw is a header-only library containing FFTW bindings for the
    xtensor C++ multi-dimensional array library.
  dev_url: https://github.com/xtensor-stack/xtensor-fftw

extra:
  recipe-maintainers:
    - egpbos
    - SylvainCorlay
    - JohanMabille
