{% set name = "xtensor-fftw" %}
{% set version = "0.2.5" %}
{% set sha256 = "7498cc597d4e32d054395fb6dab662038241032aca9a8b63771341a45af38ade" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/egpbos/xtensor-fftw/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake
    - cmake >=3.1.3
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - xtensor
    - fftw
  run:
    - xtensor >=0.16.0
    - fftw >=3.0

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-fftw  # [unix]
    - test -f ${PREFIX}/include/xtensor-fftw/xtensor-fftw_config.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-fftw/xtensor-fftwConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-fftw/xtensor-fftwConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtensor-fftw\xtensor-fftw_config.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-fftwConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-fftwConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/egpbos/xtensor-fftw
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'FFTW bindings for xtensor'
  description: |
    xtensor-fftw is a header-only library containing FFTW bindings for the
    xtensor C++ multi-dimensional array library.
  dev_url: https://github.com/egpbos/xtensor-fftw

extra:
  recipe-maintainers:
    - egpbos
